### ISSUE TITLE
Bugos a lottó telepítsek újat? Kapok érte jutalmat? :D

### ISSUE THREAD

**Issue by andris155** [Furasct/TheOld-Crafters-SavSziget#15]

**Comment by Pentarger** [comment]
Vicces xd Elég neki egy /lottery draw, és újra menni fog. :D

**Comment by andris155** [comment]
Valami elég komoly chunk bugja van.

**Comment by andris155** [comment]
Nem tudnád lecserélni erre? https://www.spigotmc.org/resources/lottery-unofficial-update.16801/

**Comment by Pentarger** [comment]
Lecserélem :D

**Comment by andris155** [comment]
Köszi mester!
