### ISSUE TITLE
javaslat acidmoney

### ISSUE THREAD

**Issue by skrisz0101** [Furasct/TheOld-Crafters-SavSziget#20]
az acidmoney eladás nem éri meg a /spawn beváltónál, és a /warp vip vip store-ban sem, 16 acid-ért azaz 1600$-ért kb nem fog venni senkise 1db halat és a víz affinitás encsi is felesleges, 1 acidmoney kb 100$ , ugy kéne gondolkozni :D

**Comment by Pentarger** [comment]
A következő updateban ez is javításra kerül! ;)
