### ISSUE TITLE
V.I.P.+ jog

### ISSUE THREAD

**Issue by AwesomeFM** [Furasct/TheOld-Crafters-SavSziget#23]
A V.I.P.+-nak nincs joga a /is top parancsra.

**Comment by Pentarger** [comment]
Köszönöm.

**Comment by andris155** [comment]
A Tagnak sincs nem? Mert a V.I.P.+ a prémiumra épül. A prémium az elitre stb... Melyik rangnak kellene ilyen jogának lennie?

**Comment by Pentarger** [comment]
A tagoknak elvileg megy, legalább is tőlük panaszt nem kaptam.

**Comment by Pentarger** [comment]
Javítva.

**Comment by andris155** [comment]
Leírhatnád Facebook-on hogy javítottad. Köszönöm.
