### ISSUE TITLE
End-Portál Hiba

### ISSUE THREAD

**Issue by poma123** [Furasct/TheOld-Crafters-SavSziget#24]
@andris155 Nem lehet beletenni az ender szemet az end-portálba. Ha bele akarom tenni(jobb katt), azt írja: "Ezt nem ütheted ki: End Portal Frame (#120:2)"

**Comment by poma123** [comment]
és ebből következtetve kiütni sem lehet.

**Comment by andris155** [comment]
Most jó?

**Comment by poma123** [comment]
Nem jó

**Comment by andris155** [comment]
A tulaj kitudja ütni. Aktiválni meg úgy sem lehet. Csak a generált aktiválható ender szemmel.

**Comment by andris155** [comment]
WorldEdit-el a tulaj tud lerakni portált bele.

**Comment by andris155** [comment]
120 a széle a portál meg 119

**Comment by poma123** [comment]
De ha küldetések is lesznek ami end-portált ad, így akkor nem lehet endbe menni, nem?

**Comment by Pentarger** [comment]
@andris155 belemegyek a portálba és ugyan oda dob vissza. Tehát, nem visz el az Endbe.

**Comment by andris155** [comment]
indítsd újra a szervert

**Comment by andris155** [comment]
meghülyült a plugin kicsit xd

**Comment by Pentarger** [comment]
"No specifis end world has benn linked to this world and 'Spawn_The_End' is not a world"

**Comment by poma123** [comment]
Multiverse

**Comment by Pentarger** [comment]
Már javítva!
