### ISSUE TITLE
További Szükséges Staff jogok

### ISSUE THREAD

**Issue by poma123** [Furasct/TheOld-Crafters-SavSziget#25]

**Comment by poma123** [comment]
### Moderátor:
/co i
/payoff
/payon
/enderchest
/craft
//pos1
//pos2
//distr - (Blokkok megnézése a kijelölt területen)
Instant teleportálás (amikor nincs az a 3 másodperces visszaszámlálás)

**Comment by Pentarger** [comment]
Worldedit Admintól van, craft felesleges, hisz kreatív jogod van.
Amit engedélyeztem: ./co i, /ec játékos, Instant Teleportálás

**Comment by poma123** [comment]
köszi

**Comment by poma123** [comment]
@Furasct Kellene valami, amivel meg lehet nézni, hogy ki back-elt az eventen. Nehéz követni ki hol halt meg és hova teleportált vissza.

**Comment by andris155** [comment]
Szerintem erre csak az a megoldás, hogy külön event világ amiben már megtudom oldani ha ott meghal ne tudjon oda vissza back-elni.
