### ISSUE TITLE
Nether Spawnerek

### ISSUE THREAD

**Issue by poma123** [Furasct/TheOld-Crafters-SavSziget#30]
Mitől függ, hogy kinek milyen spawner jut? A leggyakoribb az a malac spawner, de van akinek van ghost vagy blaze spawnere.

**Comment by andris155** [comment]
Elvileg a régiek malacok egy bug miatt. Viszont az újak talán már jól spawnolnak le.

**Comment by andris155** [comment]
Szóval ha az újak jók akkor javított hiba. A régiekkel nem lehet mit tenni. Max a /spawner-el megváltoztatni.
