### ISSUE TITLE
Banki XP kivét probléma

### ISSUE THREAD

**Issue by Icecroft** [Furasct/TheOld-Crafters-SavSziget#33]
Jelenleg a bankba csak az összes XP-t tehetem be és vehetem ki.
Ha fix összeget akarok kivenni, akkor hibát jelez:
ha 1000 XP-t akarok kivenni a 36k-ból és beírom a chat ablakba az 1000 -et, akkor a hiba az, hogy nincs elég XP-m. Ha 1000.00-t írok a chat ablakba, akkor a hibaüzenet, hogy túl nagy vagy túl kis összeget adtam meg.

**Comment by Pentarger** [comment]
Nem találtunk hibát. Nekünk tökéletesen működött. Lehet, hogy nincs bent annyi XP -d a bankban, mint amennyit ki szeretnél venni.
