### ISSUE TITLE
A kemencéből XP

### ISSUE THREAD

**Issue by Eukalp** [Furasct/TheOld-Crafters-SavSziget#34]
A kemencéből ha kiveszem kapok xp-t de ha ugy veszem ki hogy számokkal pl 1,2,8 vagy ilyesmi akkor nem kapok xp-t

**Comment by andris155** [comment]
Ez játék hiba lesz szerintem nem szerver.

2017. szept. 5. 16:15 ezt írta ("TamasB14" <notifications@github.com>):
