### ISSUE TITLE
Hajóval átszökni a keritésen és az ajtós trükk

### ISSUE THREAD

**Issue by Eukalp** [Furasct/TheOld-Crafters-SavSziget#35]
Ha van valaki aki nem szereti ha a szigetén vannak de van welcome táblája és keritéssel van az a pont megcsinálva pl.: egy üzlet akkor ha a kerités elé a vizre rakok hajót és arra beleülök ki szöktem és az ajtóval lehet a bugos dolgot használni az az ha magamra nyitom rá ugrok és még egyszer és akkor fent is vagyok

**Comment by Pentarger** [comment]
Ha zavar a szigeteden egy bizonyos játékos, akkor használd az **/is ban** parancsot, így nem fog tudni kiszökni.
