### ISSUE TITLE
Érinthető hologram.

### ISSUE THREAD

**Issue by andris155** [Furasct/TheOld-Crafters-SavSziget#37]
Van elvileg olyan plugin, amivel ha jobb klikkelnek erre kiírja a chat-re és megtudják onnan nyitni. De így szerintem kézzel lusták lemásolni ezt az emberek.
![2017-09-06_19 20 04](https://user-images.githubusercontent.com/8324198/30125399-94c3a106-9338-11e7-81bc-1e067822e1ab.png)

**Comment by Pentarger** [comment]
Meglesem.

**Comment by andris155** [comment]
https://dev.bukkit.org/projects/touchscreen-holograms

**Comment by Pentarger** [comment]
Erre még várni kell. :/

"At me this plugin isn'T kompaktibel with the last version of HologrammDisplay and Spigot 1.12. The plugin send never errors or warnings, but after click to the hologramm the server down't get any command via Touchscreen Holograms."

**Comment by andris155** [comment]
:/

**Comment by Pentarger** [comment]
A hologramok számát csökkentettem. Információnak már csak a FB oldal linkje van kint, azt pedig nem nehéz lemásolni.
