### ISSUE TITLE
Küldetések helyesebb fordítása

### ISSUE THREAD

**Issue by balazzrthd** [Furasct/TheOld-Crafters-SavSziget#38]

**Comment by balazzrthd** [comment]
Mindig ENTERT nyomok tehát sajnálom ismét.

Az lenne a problémám hogy ma pl.  megcsináltam 1 küldetést amire megvolt mindenem...
De az volt a gond hogy nem megfelelően írta hogy mi kell. Csak azt írta:1 térkép , mikor egy megnyitott / használt térképet kért. Elég sok időt vaciláltam ezzel ! Kérlek a jövőben kicsit még érthetőbben / pontosabban írjátok le amit kér a küldetés!:)

**Comment by Pentarger** [comment]
Ha lesz időm, akkor meglesem. :)
