### ISSUE TITLE
hiba.

### ISSUE THREAD

**Issue by Sherox** [Furasct/TheOld-Crafters-SavSziget#5]
Ha Shiftelve Kimész egy Lekapált Föld Szélére Úgy Hogy Ott a víz Akkor elkezd Sebezni

Amikor Új Szigetet Kezdesz Akkor a "Sherox a Víz Sebez" tábla alatt a blockot nem lehet kiütni.

-./Sherox/.-

**Comment by andris155** [comment]
Szerintem erre nincs javítás.

**Comment by andris155** [comment]
Meg ez nem is hiba, hiszen az a föld alacsonyabb.
