### ISSUE TITLE
Brutál fokozatos küldetésen a golemes küldetés probléma

### ISSUE THREAD

**Issue by Eukalp** [Furasct/TheOld-Crafters-SavSziget#50]
van egy olyan dolog hogy
nincs egy megfelelő tárgyad: 1 iron golem 
és alá meg azt irja
nincs 10 megfelelő tárgyad a.....

**Comment by Pentarger** [comment]
A többi játékosnak tökéletesen működik. Szerintem, nálad lesz a hiba.
