### ISSUE TITLE
/ec hiba

### ISSUE THREAD

**Issue by Antipixelhun** [Furasct/TheOld-Crafters-SavSziget#59]
Segítőként nincs jog /ec-ni (/enderchest-el se).

**Comment by Pentarger** [comment]
@andris155 kérlek elintézed?

**Comment by poma123** [comment]
@andris155 jelenleg még mindig nincs.

**Comment by andris155** [comment]
Más ec-jét is lássák és módosítani is tudják?

**Comment by Pentarger** [comment]
Legyen úgy, ahogy S1 -en van.

**Comment by andris155** [comment]
Beállítottam, de a /oe név értelmesebb, mivel offline is megy.
