### ISSUE TITLE
Halhatatlannak lenni savban

### ISSUE THREAD

**Issue by Eukalp** [Furasct/TheOld-Crafters-SavSziget#6]
van a vizen 1 fadeszka és arra teszek lépcsőt majd ha ráülök és átváltom a skinem halhatatlan lettem a sav ellen és az eső se fog sebezni

**Comment by andris155** [comment]
Azokat a szerencsétlen protocolokat nem jó bugoltatni. xd

**Comment by andris155** [comment]
lépcső nélkül is megy a skinnel?

**Comment by poma123** [comment]
Hajóban ülve is ugyanez lesz

**Comment by andris155** [comment]
Szerintem akkor ezt nem tudjuk javítani.

**Comment by Eukalp** [comment]
És ha ülés közben nem lehetne ./skin parancsot használni?

**Comment by Eukalp** [comment]
csak akkor mükszik ha ülve váltod átt
