### ISSUE TITLE
ChatControl

### ISSUE THREAD

**Issue by poma123** [Furasct/TheOld-Crafters-SavSziget#63]

**Comment by andris155** [comment]
Berakva. A jogok hozzá:
Alap rang:
- chatcontrol.commands.ignore
- chatcontrol.commands.reply
- chatcontrol.commands.tell
Színes írásos rang:
- chatcontrol.chat.format.color
- chatcontrol.chat.format.reset
Chat formázásos rang:
- chatcontrol.chat.format.bold
- chatcontrol.chat.format.italic
- chatcontrol.chat.format.strikethrough
- chatcontrol.chat.format.underline
Segítő:
- chatcontrol.commands.adminchat
- chatcontrol.bypass.rules
- chatcontrol.commands.adminchat
- chatcontrol.notify.ad
- chatcontrol.notify.signduplication
- chatcontrol.notify.swear
- chatcontrol.commands.clear
Moderátor:
- chatcontrol.bypass.time.chat
- chatcontrol.bypass.time.commands
- chatcontrol.bypass.ad

**Comment by andris155** [comment]
Ja és az essentials privát üzenet, és ignore jogot ne felejtsétek elvenni az alap rangtól.

**Comment by andris155** [comment]
Admin jogok:
- chatcontrol.spy.autoenable
- chatcontrol.bypass.spy
- chatcontrol.commands.spy

**Comment by poma123** [comment]
<3
